### ISSUE TITLE
Failed to convert tool to task no tool calls found, asking user

### ISSUE THREAD

**Issue by Eno654** [semanser/codel#61] opened 2024-04-05 14:19 UTC
Still doesn't work.
"There was an error getting the next task. What should I do next?"

**Comment by semanser** [comment] 2024-04-05 14:30
just to double check again: did you run `docker pull ghcr.io/semanser/codel:latest`?

**Comment by Eno654** [comment] 2024-04-05 14:38
Yes, I did.
docker run \
  -e OPEN_AI_KEY=your_open_ai_key \
  -e OPEN_AI_MODEL=gpt-4-0125-preview \
  -e OLLAMA_MODEL=llama2 \
  -p 3000:8080 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  ghcr.io/semanser/codel:latest

cmd as administrator and without the \

**Comment by semanser** [comment] 2024-04-05 14:41
Is it happening every time for every task that you're giving? I just looks very similar to latest issue and I'm pretty confident that it's been resolved in with the latest release. 

Just trying to figure out what could possible cause it again... I'm not able to reproduce it this time (at least not in 100% of cases).

**Comment by Eno654** [comment] 2024-04-05 14:42
I had run this again:
docker run \
  -e OPEN_AI_KEY=your_open_ai_key \
  -e OPEN_AI_MODEL=gpt-4-0125-preview \
  -e OLLAMA_MODEL=llama2 \
  -p 3000:8080 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  ghcr.io/semanser/codel:latest

Ran the docker pull but same problem happening. Seems to be using OpenAI API credits so that's not an issue anymore.

**Comment by Eno654** [comment] 2024-04-05 14:43
Yes, happens for every task I'm giving it.

**Comment by semanser** [comment] 2024-04-05 14:49
Could you post all the terminal output after you run your container? No need to run any task, just start Codel.

**Comment by Eno654** [comment] 2024-04-05 14:52
Doesn't give that error anymore. Seems to be working. Don't know what changed other than me reinitializing the whole docker run

**Comment by semanser** [comment] 2024-04-05 14:56
@Eno654 maybe now it uses the correct latest version (idk why it wasn't before 😓). Closing the issue. Feel free to comment if the problem appears again.

**Closed as completed by semanser** 2024-04-05 14:56 UTC
Labels: bug, needs-repro-steps

**Comment by James4Ever0** [comment] 2024-07-31 05:37
I have the same problem just as described. I now plan to use this thing as a library or case study.

```
2024/07/31 05:35:03 Spawning container python:latest "codel-terminal-3"
2024/07/31 05:35:03 Image python:latest found locally: true
2024/07/31 05:35:03 Creating container codel-terminal-3...
2024/07/31 05:35:03 Container codel-terminal-3 created
2024/07/31 05:35:03 Container codel-terminal-3 started
2024/07/31 05:35:03 Getting next task
2024/07/31 05:35:06 Failed to convert tool to task no tool calls found, asking user
2024/07/31 05:35:06 Command 11 added to the queue 3
2024/07/31 05:35:06 Waiting for a task
2024/07/31 05:35:06 Processing command 11 of type ask
2024/07/31 05:35:06 Waiting for a task

```
